[tool.poetry]
name = "pennylane-ket"
version = "0.1.0"
description = "Ket PennyLane plugin"
authors = ["Evandro Chagas Ribeiro da Rosa <ev.crr97@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
ket-lang = "^0.4"
PennyLane = "^0.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."pennylane.plugins"]
"ket" = "pennylane_ket:KetDevice"