[tool.poetry]
name = "kilroy-face-discord"
version = "0.5.1"
description = "kilroy face for Discord ðŸŽ®"
readme = "README.md"
authors = ["kilroy <kilroymail@pm.me>"]
classifiers = ["License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"]
repository = "https://github.com/kilroybot/kilroy-face-discord"
documentation = "https://kilroybot.github.io/kilroy-face-discord"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
typer = { version = "^0.6", extras = ["all"] }
kilroy-face-server-py-sdk = "~0.7"
hikari = "2.0.0.dev109"
aiostream = "^0.4"
PyYAML = "^6.0"
deepmerge = "^1.0"
platformdirs = "^2.5"

# dev

# test
pytest = { version = "^7.0", optional = true }

[tool.poetry.extras]
# need to do it that way until poetry supports dependency groups: https://github.com/python-poetry/poetry/issues/1644
dev = ["pytest"]
test = ["pytest"]
[tool.poetry.scripts]
# cli entry point
kilroy-face-discord = "kilroy_face_discord.__main__:cli"

[build-system]
# this should be there, see https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
