[tool.poetry]
name = "trier"
version = "1.0.2"
description = "Utility wrapper to handle exceptions."
authors = ["Arnold Anthonypillai <arnoldbronson16@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.19.0"
pytest = "^7.1.2"
pre-commit = "^2.20.0"
tox = "^3.25.1"
scriv = {extras = ["toml"], version = "^0.16.0"}
coverage = "^6.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.scriv]
format = "md"
version = "literal: src/trier/__init__.py: __version__"
