[tool.poetry]
authors = ["Craig Trim <craigtrim@gmail.com>"]
description = "Perform runtime tagging and annotation of unstructured text"
name = "dbpedia-tag"
version = "0.1.12"

[tool.poetry.dependencies]
baseblock = "*"
dbpedia-ent = "*"
fast-sentence-tokenize = "*"
python = "3.8.5"

[tool.poetry.dev-dependencies]
autopep8 = "*"
pytest = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
